<pre class='metadata'>
Title: DiSHACLed Dataset and Data Service Discovery
Shortname: DiSHACLed-Discovery
Level: 1
Status: LD
Markup Shorthands: markdown yes
URL: https://dishacled.github.io/discovery-specification/
Repository: https://github.com/DiSHACLed/discovery-specification/
Editor: Julián Rojas, Ghent University - imec http://idlab.ugent.be/, julianandres.roajsmelendez@ugent.be
Abstract: This specification defines an algorithm and the logical processes for a client application to discover a (set of) RDF dataset(s) and/or data service(s) from one or more DCAT-AP data catalogs, based on a given input SHACL shape or SPARQL query.
</pre>

<pre class='biblio'>
{
    "LDPATTERNS": {
    "authors": [
      "Leigh Dodds",
      "Ian Davis"
    ],
    "href": "http://patterns.dataincubator.org/book/",
    "title": "Linked Data Patterns: A pattern catalogue for modelling, publishing, and consuming Linked Data",
    "date": "May 2012"
  }
}
</pre>

# Introduction # {#introduction}
LINKEDDATAPATTERNS
The DCAT Application Profile for data portals (DCAT-AP) [[!DCAT-AP]] is the [official standard in Europe](https://interoperable-europe.ec.europa.eu/collection/semic-support-centre/solution/dcat-application-profile-data-portals-europe) 
for describing datasets and data services in catalogues on the Web. 
It provides a common model that enables interoperability across data portals, making it easier to publish and share metadata consistently. 
This interoperability has been instrumental in improving the visibility and accessibility of open data across domains and EU member states.

However, the current design and usage of DCAT-AP are primarily oriented towards human-driven discovery. 
Catalogues are typically accessed through graphical interfaces where users browse, filter, and search for resources based on keywords or metadata attributes. 
While this supports transparency and accessibility for a wide audience, it limits the potential for automated, machine-based discovery and integration of datasets and data services. 
In practice, many use cases—such as federated analytics, cross-domain applications, or dynamic data integration pipelines—require more than keyword search: 
they need support for automated identification of datasets and services that match specific structural and semantic requirements.

This specification, aims to address this gap by defining a (i) data model extension for DCAT-AP that allows describing sematically
what is contained within RDF [[!RDF11-CONCEPTS]] datasets and expected/produced by RDF data services; 
and an (ii) algorithm for automated discovery and selection of RDF datasets and RDF data services over DCAT-AP catalogues, 
based on formal input constraints expressed as either:

- a [[!SHACL]] shape, describing the expected structure and semantics of the data, or
- a [[!SPARQL-QUERY]], representing the information needs directly.

By enabling discovery through such formal specifications, the proposed approach allows clients 
to automatically determine the relevance of available resources, thereby supporting machine-to-machine interoperability. 
This contributes to realising the full potential of DCAT-AP not only as a tool for publishing metadata for humans 
but also as a foundation for automated data ecosystems.

## Document Conventions ## {#conventions}

Within this document, the following namespace prefix bindings are used:

<table class='def'>
    <tbody>
        <tr>
            <th><strong>Prefix</strong></th>
            <th><strong>Namespace IRI</strong></th>
            <th><strong>Description</strong></th>
        </tr>
        <tr>
            <td>dcat:</td>
            <td><a href='http://www.w3.org/ns/dcat#'>http://www.w3.org/ns/dcat#</a></td>
            <td>[[!VOCAB-DCAT-3]]</td>
        </tr>
        <tr>
            <td>dcterms:</td>
            <td>http://purl.org/dc/terms/</td>
            <td>[[!DCTERMS]]</td>
        </tr>
        <tr>
            <td>rdf:</td>
            <td>http://www.w3.org/1999/02/22-rdf-syntax-ns#</td>
            <td>[[!RDF11-SCHEMA]]</td>
        </tr>
        <tr>
            <td>rdfs:</td>
            <td>http://www.w3.org/2000/01/rdf-schema#</td>
            <td>[[!RDF11-SCHEMA]]</td>
        </tr>
        <tr>
            <td>sh:</td>
            <td>http://www.w3.org/ns/shacl#</td>
            <td>[[!SHACL]]</td>
        </tr>
        <tr>
            <td>xsd:</td>
            <td>http://www.w3.org/2001/XMLSchema#</td>
            <td>[[!XMLSCHEMA11-2]]</td>
        </tr>
    </tbody>
</table>

## Terminology ## {#terminology}

- **Dataset** refers to the definition given in [[!VOCAB-DCAT-3]] for `dcat:Dataset`.
- **Distribution** refers to the definition given in [[!VOCAB-DCAT-3]] for `dcat:Distribution`.
- **Data Service** refers to the definitions given in [[!VOCAB-DCAT-3]] for `dcat:DataService`.
- **Resource** refers to the generic term encompassing datasets, Distributions and data services, defined in [[!VOCAB-DCAT-3]] as `dcat:Resource`
- **Catalog** refers to a [[!VOCAB-DCAT-3]] resource of type `dcat:Catalog`.
- **Shape** refers to a [[!SHACL]] `sh:NodeShape` that formally describes constraints over RDF data.
- **Discovery** refers to the process specified in [[#logical-flow]] for identifying relevant RDF Resources over one or more Catalogs.
- **Client** refers to a client application that implements the [[#algorithm]] and supports the [[#logical-flow]]. 

# Describing DCAT(-AP) resource content with shapes # {#dcat-shapes}

This section defines a set of alternative ways in which DCAT(-AP) resources referring to RDF datasets/data services,
can be extended to include references to data Shapes that semantically describe their content.  
The extensions are designed to be minimal and compatible with existing DCAT-AP profiles.

Note: The [[#logical-flow]] and related [[#algorithm]] are designed to support all the following data model extensions.
In the presence of more than one alternative, a discovery client will not prioritise any of them and should treat them as a logical OR relation.     

## Relating to shapes via `dcterms:conformsTo` ## {#conforms-to}

In this approach we establish the use of the existing property `dcterms:conformsTo` [[!DCTERMS]], 
as described by [[!VOCAB-DCAT-3]] and [[!DCAT-AP]], to link an RDF resource defined as part of a catalog,
to a shape that describes its content.

In [[!VOCAB-DCAT-3]], the use of `dcterms:conformsTo` is informally suggested for linking a resource to a relevant standard,
that specifies its model, **schema**, ontology, application profile, among others.
SHACL shapes may be considered as a type of schema, as they define the structure and constraints that RDF instance data must adhere to.

No further clarifications are provided in [[!DCAT-AP]] regarding the expected use of `dcterms:conformsTo`,
beyond the informal suggestion to link to relevant standards, understood as instances of `dcterms:Standard`.

**Figure 1** shows how any kind of RDF resource that has been declared in a catalog, may be linked to a related shape via `dcterms:conformsTo`.

<figure>
    <figcaption>
        DCAT Resources linked to a SHACL shape via `dcterms:conformsTo`. 
    </figcaption>
    <object type='image/svg+xml' data='img/figure-1.svg' width='600'></object>
</figure>

Next, examples 1-3 show corresponding RDF representations for a dataset, distribution, and data service, respectively linked to their shapes.

<div class='example' highlight='turtle'>
RDF representation of a `dcat:Dataset` linked to a shape via `dcterms:conformsTo`
```turtle
ex:myDataset a dcat:Dataset;
    dcterms:title "My Dataset";
    dcterms:conformsTo ex:myShape.

ex:myShape a sh:NodeShape;
    sh:targetClass ex:MyClass;
    sh:property [
        sh:path ex:myProperty;
        sh:datatype xsd:string;
        sh:minCount 1;
    ].
```
</div>

<div class='example' highlight='turtle'>
RDF representation of a `dcat:Distribution` linked to a shape via `dcterms:conformsTo`
```turtle
ex:myDataset a dcat:Dataset;
    dcterms:title "My Dataset";
    dcat:distribution ex:myDistribution.
    
ex:myDistribution a dcat:Distribution;
    dcat:downloadURL <https://example.org/dataset.ttl>;
    dcat:mediaType <https://www.iana.org/assignments/media-types/text/turtle>
    dcterms:conformsTo ex:myShape.

ex:myShape a sh:NodeShape;
    sh:targetClass ex:MyClass;
    sh:property [
        sh:path ex:myProperty;
        sh:datatype xsd:string;
        sh:minCount 1;
    ].
```
</div>

<div class='example' highlight='turtle'>
RDF representation of a `dcat:DataService` linked to a shape via `dcterms:conformsTo`  
```turtle
ex:myService a dcat:DataService;
    dcat:endpointURL <https://example.org/my-data/service>
    dcterms:title "My data service";
    dcterms:conformsTo ex:myShape.

ex:myShape a sh:NodeShape;
    sh:targetClass ex:MyClass;
    sh:property [
        sh:path ex:myProperty;
        sh:datatype xsd:string;
        sh:minCount 1;
    ].
```
</div>

Note: A related shape to a data service could be referring to the constraints of either the input or output data (or both) of such service.
Via the `dcterms:conformsTo` property, no distintion can be made about the role of a related shape 
(see [[#qualified-relation]] for an alternative where is possible). 
However, linking multiple shapes to a data service should not entail any conflicts for the discovery process, 
given its inclusive nature based on a logical OR operation. 

## Relating to shapes via `dcat:qualifiedRelation` ## {#qualified-relation}

In this approach we establish the use of the property `dctat:qualifiedRelation` as described by [[!VOCAB-DCAT-3]] and [[!DCAT-AP]], 
to indirectly link, following an n-ary/qualified relationship pattern [[SWBP-N-ARYRELATIONS]] [[LDPATTERNS]], an RDF resource defined as part of a catalog, 
to a shape that describes its content.

In [[!VOCAB-DCAT-3]], the use of `dcat:qualifiedRelation` is informally specified as a way to define sematically richer relations
among resources. This is accomplished with the introduction of the `dcat:Relationship` class, on which specific roles can set,
to further describe the nature of the relationship between a resource and another asset.
For specifying types of roles, the use of controlled vocabularies is encouraged, which is reflected by the exsiting subclass relation
between the `dcat:Role` class and `skos:Concept`.

No further guidelines nor usage notes are given for `dcat:qualifiedRelation` and `dcat:Relationship` in [[!DCAT-AP]].

**Figure 2** shows how a shape can be linked to any type of resource using the `dcat:qualifiedRelation` property.

<figure>
    <figcaption>
        DCAT Resources linked to a SHACL shape via `dcat:qualifiedRelation`. 
    </figcaption>
    <object type='image/svg+xml' data='img/figure-2.svg' width='600'></object>
</figure>

For the discovery process, this specification does not mandate a specific role concept value via `dcat:hadRole`. 
A discovery client must assess all existing qualified relations, in search for an associated shape (see [[#logical-flow]]).

Note: [[!VOCAB-DCAT-3]] suggests the use of coded term lists such as [[IANA-RELATIONS]], or [[ISO-19115-1]],
to specify a `dcat:Relationship` role via the `dcat:hadRole` property.
However, none of the recommended vocabularies defines a specific role type that conveys a relationship between a resource and an associated shape. 
A semantically close role type is the `describedby` relation defined by [[IANA-RELATIONS]].

## Reusing `sh:shapesGraph` ## {#shapes-graph}

TODO


# Discovery logical flow # {#logical-flow}

This section describes the logical steps that a client follows to perform a discovery process.

## Initializing a client with a url ## {#starting-from}

TODO

## Selecting a dataset via shapes ## {#dataset-shapes}

TODO

## Selecting a data service via shapes ## {#data-service-shapes}

TODO

## Selecting a dataset via queries ## {#dataset-queries}

TODO

## Selecting a data service via queries ## {#data-service-queries}

TODO

# Algorithm specification # {#algorithm}

TODO